export const GET_SKILLS = 'GET_SKILLS'
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS'
export const GET_SKILLS_FAILED = 'GET_SKILLS_FAILED'

export const SEND_REQUEST = 'SEND_REQUEST'
export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS'
export const SEND_REQUEST_FAILED = 'SEND_REQUEST_FAILED'
